# Docker-compose script for database
version: '3'
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: mega
      POSTGRES_PASSWORD: mega
      POSTGRES_DB: mega
    volumes:
      - database-mega:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
volumes:
  database-mega:
